spring.application.name=ElectroNest
spring.profiles.active=local
spring.servlet.multipart.max-file-size=15MB
spring.servlet.multipart.max-request-size=80MB
spring.web.error.include-message=never
spring.web.error.include-stacktrace=never
spring.web.error.include-binding-errors=never
